# Generated by Django 5.2.5 on 2025-09-10 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_room_capacity_room_updated_at_roommember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room', 'is_banned'], name='collab_room_room_id_3a3909_idx'),
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uniq_room_user'),
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('room',), name='uniq_owner_per_room'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collab.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='collab_mess_room_id_503c4f_idx'),
        ),
    ]
