# Generated by Django 5.2.5 on 2025-09-11 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_message_alter_roommember_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roommember',
            name='uniq_owner_per_room',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='collab_mess_room_id_503c4f_idx',
        ),
        migrations.AddField(
            model_name='roommember',
            name='open_conn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='collab_mess_room_id_c3a84a_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room', 'open_conn'], name='collab_room_room_id_aa0f13_idx'),
        ),
    ]
